name = "recipe-easy"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "recipe-easy-production"

[[d1_databases]]
binding = "DB"
database_name = "recipe-easy-db"
database_id = "1b73b4ba-f095-4151-8f5c-489b59917156"

[[r2_buckets]]
binding = "RECIPE_IMAGES"
bucket_name = "recipe-images"

[vars]
ENVIRONMENT = "development"
