-- Rebuild Neon schema for RecipeEasy
-- Generated at: 2026-02-25

BEGIN;

-- Clean legacy tables from previous product shape and old attempts.
DROP TABLE IF EXISTS
  template_categories,
  recipe_template_versions,
  execution_templates,
  source_inputs,
  parsed_contents,
  content_assets,
  performance_logs,
  recipe_runs,
  recipe_templates,
  categories,
  credit_transactions,
  cuisines_i18n,
  cuisines,
  ingredient_categories_i18n,
  ingredient_categories,
  ingredients_i18n,
  ingredients,
  recipes_i18n,
  recipes,
  languages,
  model_usage_records,
  recipe_images,
  user_credits
CASCADE;

CREATE TABLE languages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  native_name TEXT NOT NULL,
  is_default BOOLEAN DEFAULT FALSE,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE ingredient_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  name TEXT
);

CREATE TABLE ingredient_categories_i18n (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT NOT NULL,
  language_code TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(category_id, language_code),
  CONSTRAINT ingredient_categories_i18n_category_fk
    FOREIGN KEY (category_id) REFERENCES ingredient_categories(id) ON DELETE CASCADE,
  CONSTRAINT ingredient_categories_i18n_language_fk
    FOREIGN KEY (language_code) REFERENCES languages(code) ON DELETE CASCADE
);

CREATE TABLE ingredients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  category_id BIGINT,
  nutritional_info TEXT,
  allergen_info TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  name TEXT,
  CONSTRAINT ingredients_category_fk
    FOREIGN KEY (category_id) REFERENCES ingredient_categories(id)
);

CREATE TABLE ingredients_i18n (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ingredient_id BIGINT NOT NULL,
  language_code TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE cuisines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  slug TEXT,
  css_class TEXT DEFAULT 'cuisine-other'
);

CREATE TABLE cuisines_i18n (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cuisine_id BIGINT NOT NULL,
  language_code TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  slug TEXT,
  UNIQUE(cuisine_id, language_code),
  CONSTRAINT cuisines_i18n_cuisine_fk
    FOREIGN KEY (cuisine_id) REFERENCES cuisines(id) ON DELETE CASCADE,
  CONSTRAINT cuisines_i18n_language_fk
    FOREIGN KEY (language_code) REFERENCES languages(code) ON DELETE CASCADE
);

CREATE TABLE recipes (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  cooking_time INTEGER,
  servings INTEGER,
  difficulty TEXT,
  ingredients TEXT,
  seasoning TEXT,
  instructions TEXT,
  tags TEXT,
  chef_tips TEXT,
  user_id TEXT,
  cuisine_id BIGINT,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ
);

CREATE TABLE recipes_i18n (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipe_id TEXT NOT NULL,
  language_code TEXT NOT NULL,
  title TEXT,
  description TEXT,
  ingredients TEXT,
  seasoning TEXT,
  instructions TEXT,
  chef_tips TEXT,
  tags TEXT,
  difficulty TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(recipe_id, language_code),
  CONSTRAINT recipes_i18n_recipe_fk
    FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE
);

CREATE TABLE recipe_images (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  recipe_id TEXT NOT NULL,
  image_path TEXT NOT NULL,
  expires_at TIMESTAMPTZ,
  image_model TEXT,
  created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE model_usage_records (
  id TEXT PRIMARY KEY,
  model_name TEXT NOT NULL,
  model_type TEXT NOT NULL,
  user_id TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE user_credits (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL UNIQUE,
  credits INTEGER NOT NULL DEFAULT 0,
  total_earned INTEGER NOT NULL DEFAULT 0,
  total_spent INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE credit_transactions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  type TEXT NOT NULL,
  amount INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_cuisines_i18n_cuisine_lang ON cuisines_i18n(cuisine_id, language_code);
CREATE INDEX idx_ingredient_categories_i18n_category ON ingredient_categories_i18n(category_id);
CREATE INDEX idx_ingredient_categories_i18n_category_lang ON ingredient_categories_i18n(category_id, language_code);
CREATE INDEX idx_ingredient_categories_i18n_language ON ingredient_categories_i18n(language_code);
CREATE INDEX idx_ingredient_categories_slug ON ingredient_categories(slug);
CREATE INDEX idx_ingredients_category ON ingredients(category_id);
CREATE INDEX idx_ingredients_slug ON ingredients(slug);
CREATE INDEX idx_recipes_i18n_language ON recipes_i18n(language_code);
CREATE INDEX idx_recipes_i18n_recipe_id ON recipes_i18n(recipe_id);
CREATE INDEX idx_recipes_i18n_recipe_lang ON recipes_i18n(recipe_id, language_code);
CREATE INDEX idx_user_credits_user_id ON user_credits(user_id);

COMMIT;
